spring.application.name=server

spring.datasource.url=jdbc:mysql://localhost:3306/pet_medical_mall?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.global-config.db-config.id-type=auto


# Qwen DashScope 配置
ai.api-key=sk-0db53374f3e04b5e8daa1089a851c0d3
ai.model=qwen-plus
# 前端药品详情真实地址前缀（现在改为自动搜索模式）
ai.drug-detail-base-url=http://localhost:5173/mall?keyword=
